# Generated by Django 3.2.16 on 2023-02-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
