# Generated by Django 3.2.16 on 2023-02-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_countinstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
