# Generated by Django 3.2.16 on 2023-02-15 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20230214_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStock',
            new_name='quantity',
        ),
    ]
