# Generated by Django 3.2.16 on 2023-02-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_countinstock_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
